version: '3.8'

services:
  load-balancer:
    image: nginx:1.19-alpine
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 8080:8080

  nginx-backed-1:
    image: nginx-backed-1
    container_name: nginx-backed-1
    build: .
    restart: always
    environment:
      PORT: 3000

  nginx-backed-2:
    image: nginx-backed-2
    container_name: nginx-backed-2
    build: .
    restart: always
    environment:
      PORT: 3001

  nginx-backed-3:
    image: nginx-backed-3
    container_name: nginx-backed-3
    build: .
    restart: always
    environment:
      PORT: 3002


