version: '3.8'

services:
  load-balancer:
    image: nginx:1.19-alpine
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 8080:8080
    deploy:
      placement:
        constraints: [ node.role == manager ]
    depends_on:
      - backend
    networks:
      - mynwetwork

  backend:
    image: backend-img
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    deploy:
      replicas: 3
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s
    networks:
      - mynwetwork

networks:
  mynwetwork:
    driver: overlay
