version: '3.8'

services:
  load-balancer:
    image: nginx:1.19-alpine
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 8080:8080
    depends_on:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role==manager'

  backend:
    image: backend:v1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    deploy:
      replicas: 3
      mode: replicated
      update_config:
        parallelism: 3
        delay: 10s
